import React, { useState } from 'react';
import { Dialog, Box, Typography, Button } from '@material-ui/core';

export const ConsentAgreement = (props) => {
    const [shouldDisableAcceptBtn, setShouldDisableAcceptBtn] = useState(false);

    const onConsentAccept = async () => {
        props.onUserAgreed();
        const API = process.env.NODE_ENV === 'development' ? 'http://localhost:3000' : 'https://app.lazybucks.co';
        await fetch(`${API}/extension/changeConsentStatus`, {
            method: "POST",
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                installationId: props.installationId 
            }),
        });
    };

    return (
        <Box style={{ height: '100%', width: '100%', paddingLeft: '24px', paddingRight: '24px', paddingTop: '12px', paddingBottom: '12px' }} p={5} display="flex" flexDirection="column" justifyContent="space-between">
            <Box display="flex" justifyContent="center" alignItems="center">
                <Typography variant="subtitle1">Do you agree to our Terms & Conditions?</Typography>
            </Box>
            <Box>
                <div style={{ overflow: 'scroll' }}>
                    <p><strong>GENERAL</strong></p>
                    <p>These terms and conditions (the &quot;<strong>Agreement</strong>&quot;) shall govern the relationship between you and the Company (as defined below), whereby you will provide the Company certain Services as further detailed below.</p>
                    <p>Where used in this Agreement, references to: (a) &quot;<strong>you</strong>” and/or &quot;<strong>your</strong>&quot; mean the individual or entity from which the Company receives the Services, and (b) the &quot;<strong>Company</strong>&quot; means the company that grants you the License under the activity with LazyBucks (<a href="https://lazybucks.co/" target="_blank" className="url">https://lazybucks.co/</a>)] and, &quot;<strong>we</strong>&quot;, &quot;<strong>our</strong>&quot; and &quot;<strong>us</strong>&quot; means, as applicable, the Company and any of its directors, officers, shareholders, employees, advisors, contractors, subsidiaries and any of its affiliated corporate entities.</p>
                    <p>            <strong>DEFINITIONS AND INTERPRETATION</strong></p>
                    <p>            In this Agreement, references to the following words shall have the meanings set out below:</p>
                    <p>              &quot;<strong>Fees</strong>&quot; is the amount due and payable to you by the Company, as calculated based solely on the Company&#39;s system&#39;s data and in accordance with the terms of this Agreement.</p>
                    <p>              &quot;<strong>Materials</strong>&quot; means multimedia images, graphics, text, data and any other online media and any other promotional and/or marketing materials used by the Company in connection with this Agreement..</p>
                    <p>              &quot;<strong>Profile</strong>&quot; means your profile on the Facebook social network.</p>
                    <p>              &quot;<strong>Services</strong>&quot; means the services provided to the Company in accordance with the provisions of Section 3 of this Agreement.</p>
                    <p>               </p>
                    <p>            <strong>SERVICES</strong></p>
                    <p>              You shall provide the Company with exclusive access to your Profile and allow the Company to exclusively perform various activities using the Profile; including, but not limited to, publishing the Materials on the Profile and/o performing marketing and/or promotional activities while using the Profile at the sole and absolute discretion of the Company. You shall not provide any third party with services similar and/or identical to, and/or otherwise that compete with, the Services, nor shall you allow any third party use the Profile in any form or manner.</p>
                    <p>              You shall not perform any activity which burdens in any way or manner the activities of the Company in accordance with the provisions of Section 3.1 of this Agreement including, but not limited to, removing any Materials, blocking the Company&#39;s access to the Profile, closing the Profile and/or changing any user name and/or password. You shall not remove and/or amend the Materials in any form or manner.</p>
                    <p>              You shall comply with all of the Company&#39;s requests and our instructions with respect to the Services and the Profile; including, but not limited to, removing anything from the Profile and /or adding anything to the Profile.</p>
                    <p>              You shall provide true and complete information to the Company and promptly update such information if all or any part of it changes. You shall also provide the Company with such other information as the Company may request from time to time.</p>
                    <p>              You represent and warrant that (i) you have the power and authority to enter into this Agreement and perform your obligations under this Agreement, and (ii) the Profile is owned by you and not by any third party.</p>
                    <p>              We make no representations or warranties concerning the legality of the Services and/or of the use of the Profile by the Company and/or compliance with the Facebook social network&#39;s terms and conditions, license agreement and/or any other contractual arrangement. We shall not be responsible for any liability related to the offering of the Services and/or the use of the Profile by the Company. It is Your responsibility to ensure that You comply with any and all laws applicable to You and the Facebook social network&#39;s terms and conditions, license agreement and/or any other similar contractual arrangement in connection with the provision of the Services and the use of the Profile by the Company in accordance with this Agreement before offering the Services and/or allowing the use of the Profile by the Company. If you have any doubt, you should consult with legal counsel.</p>
                    <p>              You shall immediately inform the Company of any interaction between you and Facebook Inc. and/or any other third party in relation to the Services, this Agreement and/or the use of the Profile by the Company. You shall not respond to any such interaction without informing the Company and consulting with it; any such response must be coordinated with the Company and agreed to by the Company.</p>
                    <p>               </p>
                    <p>            <strong>THE PROFILE</strong></p>
                    <p>                 Without derogating from any other provisions of this Agreement, the Profile shall not (i) pertain to alcohol, tobacco, firearms, adult or sexually oriented content or products, prostitution, politics, pharmaceuticals, illegal drugs, violence, profanity, expletives or inappropriate language, illegal conduct, illegal file sharing applications or software or devices removal; that facilitate DRM (ii) induces, promotes or facilitates infringement of intellectual property rights; (iii) promotes goods or services that enable the circumvention of copy protection technologies; (iv) promotes websites, companies or services identified in writing by the Company from time to time as involved with any of the above; (v) contains pornographic, obscene or indecent materials in nature or, in the Company’s sole discretion, might be deemed harmful to the Company’s business reputation; (vi) offers or disseminates fraudulent goods, services, schemes, or promotions; (vii) promotes illegal activity such as copyright infringement, racism, hate, mail fraud, spam, pyramid schemes; (viii) promotes or contains libelous, discriminatory or defamatory material, violates privacy rights, and/or is contrary to public policy or otherwise unlawful; and/or (ix) is otherwise unsuitable at the Company&#39;s sole discretion.</p>
                    <p>                 By entering to this contract with the Company you declare that you are at least eighteen (18) years of age or above and have full legal capacity to enter into a contract.</p>
                    <p>              If the Company determines, at its sole discretion, that you have engaged in any of the activities that contravene the provisions of Section 4.1, the Company may (without limiting any other rights or remedies available to us) terminate this Agreement with immediate effect and you will forfeit any Fees due to you.</p>
                    <p>               </p>
                    <p>            <strong>REPORTS &amp; PAYMENTS</strong></p>
                    <p>              The Company will calculate the Fees in accordance with its reporting system, and such calculation is final and unappealable. For the avoidance of doubt, and without derogating from the above, the Company retains full and absolute discretion in disregarding any event of fraud, abuse and/or other action intended to illicitly increase the Fees; in which case the Company may terminate this Agreement with immediate effect and you will forfeit any Fees due to you.</p>
                    <p>              The Fees will be paid by the Company in accordance with the terms of this Agreement, the Company&#39;s calculations and the payment plan and rates outlined at the following website:      [<a href="https://lazybucks.co/" target="_blank" className="url">https://lazybucks.co/</a>] (the &quot;<strong>Website</strong>&quot;). Any change in the Fees will enter immediately into force upon posting the updated Fees on the Website, without the need to notify you in any other form or manner. Any such change will apply to any activity taking place from the posting of the updated Fees on the Website, including in respect of any provision of Services and/or use of Profile that commenced prior to updating the Fees. The Company shall remit to you a statement of the Fees as well as the Fees within 60 days from the end of every month in respect of the activity performed during that month.</p>
                    <p>              If any overpayment is made in the calculation of the Fees the Company reserves the right to correct such calculation at any time and to reclaim from you any overpayment to you and/or withhold and/or set-off from the Fees.</p>
                    <p>              You may not, under any circumstance, deduct, set-off or withhold any sums due to us if any.</p>
                    <p>              The Fees are inclusive of any taxes, levies and/or charges (including, but not limited to, VAT); if any taxes, levies and/or charges (including, but not limited to, VAT) are levied on the Fees, the Company is under no obligation to increase the Fees in any manner whatsoever. Furthermore, if required under any applicable law, the Company has the right to withhold and/or deduct any taxes, levies and/or charges (including, but not limited to, VAT) from the Fees.</p>
                    <p>              Charges for wires or courier charges for cheques will be covered by you and deducted from the Fees. For the avoidance of doubt, we have no liability to pay any currency conversion charges or any charges associated with the transfer of monies to you.</p>
                    <p>             </p>
                    <p>            <strong>TERM AND TERMINATION</strong></p>
                    <p>              This Agreement may be terminated without cause upon the delivery at any point by the Company or 10 (ten) days by you. </p>
                    <p>              Upon termination of this Agreement: (a) you shall cease to provide the Services; (b) you shall not be entitled to any payment (save for the payment of the Fees accrued prior to the termination of this Agreement and in accordance with the provisions of this Agreement); (c) the Company reserves the right to deduct any sums owed to us from the Fees and/or withhold any payments of the Fees for a period of 6 (six) months; and (d) any Section which by the nature of its language is intended to survive the termination or expiration of this Agreement, including, but not limited to, Sections ‎3.5, ‎3.6, this Section ‎6, ‎7, ‎8, ‎9 and ‎10 shall accordingly survive such termination.</p>
                    <p>               </p>
                    <p>            <strong>LIABILITIES</strong></p>
                    <p>              WE MAKE NO WARRANTIES OR REPRESENTATIONS (WHETHER EXPRESS OR IMPLIED BY LAW, STATUTE OR OTHERWISE) WITH RESPECT TO THE MATERIALS, OR AS TO THE LEGALITY AND/OR COMPLIANCE OF THE SERVICES AND/OR THE USE OF THE PROFILE BY THE COMPANY UNDER ANY LEGISLATION, AGREEMENT, TERMS AND CONDITIONS AND/OR ANY OTHER CONTRACTUAL ARRANGEMENT BETWEEN YOU AND FACEBOOK INC. AND/OR ANY OTHER THIRD PARTY.</p>
                    <p>              Notwithstanding anything to the contrary in this Agreement, our aggregate liability to You, whether in an action based on contract, tort, warranty or any other legal theory, including, but not limited to, in connection with any liability towards Facebook Inc., shall not exceed in aggregate the sum USD 50 (fifty US Dollars) (the &quot;<strong>Sum</strong>&quot;). Other than the liability to pay the Sum, we shall not be liable for any liabilities, obligations, losses, damages, injuries, penalties, claims, suits, costs, actions, expenses and disbursements (actual or contingent), whether direct, special, indirect, incidental, punitive or consequential, including, but not limited to, damages for loss of profits, business, revenue, economic advantage, data and/or equipment, as well as any action taken by Facebook Inc. or any third party towards you and/or your Profile, whether or not these were known to us and whether or not you have informed us of such.</p>
                    <p>              The obligations under this Agreement do not constitute personal obligations of the owners, shareholders, directors, officers, contractors, agents, employees, vendors, advisors or suppliers of the Company (the &quot;<strong>Associated Persons</strong>&quot;), nor of the subsidiaries and/or affiliated corporate entities of the Company nor of their Associated Persons.</p>
                    <p>              You shall defend, indemnify and hold us harmless from and against any and all claims, demands, liabilities, losses, damages, costs and expenses (including legal fees) resulting or arising from your breach of this Agreement.</p>
                    <p>              Without prejudice to any other rights or remedies available to us under this Agreement or otherwise, we shall be entitled to set off any payments otherwise payable by us to you hereunder, against any liability of you to us, including (but not limited to) any claims we have against you resulting from or arising from, your breach of this Agreement.</p>
                    <p>               </p>
                    <p>            <strong>INTELLECTUAL PROPERTY RIGHTS</strong></p>
                    <p>              You acknowledge that the Company owns all intellectual property rights comprised in any and all of the Materials.</p>
                    <p>              If you make any amendment, addition, modification and/or derivative work in respect of the Materials, any such modification, addition, amendment and/or derivative work will be solely owned by the Company and you will have no right or title in such modification, addition, amendment and/or derivative work in any way whatsoever.</p>
                    <p>               </p>
                    <p>            <strong>CONFIDENTIAL INFORMATION</strong></p>
                    <p>              You shall keep confidential and shall not disclose to any third party any and all proprietary information or confidential information disclosed to you by us, and/or relating to our business, processes, practices, products, customers, accounts, finance or contractual arrangements or trade secrets (&quot;<strong>Confidential Information</strong>&quot;). You further agree to keep confidential and not to disclose to any third party, any of the terms and conditions of this Agreement.</p>
                    <p>               </p>
                    <p>            <strong>MISCELLANEOUS</strong></p>
                    <p>              All notices pertaining to this Agreement will be given by email delivery service system to you at the email address provided to us by you, and to us at the same email delivery service system. Any notice sent by email shall be deemed received on the earlier of an acknowledgement being received or 24 (twenty four) hours from the time of transmission.</p>
                    <p>              Subject to the provisions of Section ‎3.1, there is no relationship of exclusivity, partnership, joint venture, employment, agency or franchise between you and us under this Agreement. You do not have the authority to bind us (including the making of any representation or warranty, the assumption of any obligation or liability and/or the exercise of any right or power).</p>
                    <p>              You understand that the Company may at any time (directly or indirectly) enter into similar agreements to this Agreement with others on the same or different terms as those provided to you in this Agreement and that such terms may be similar, and even competitive, to you.</p>
                    <p>              You may not assign, license, sub-license or deal in any other manner with this Agreement or any rights under this Agreement, or sub-contract any or all of your obligations under this Agreement, or purport to do any of the same. Any purported assignment in breach of this clause shall confer no rights on the purported assignee. The Company may assign this Agreement at its sole discretion.</p>
                    <p>              This Agreement shall be governed by and construed in accordance with the laws of Pakistan without giving effect to conflict of law principles. You irrevocably agree to submit, for our benefit, to the exclusive jurisdiction of the courts of the Islamabad District, Pakistan, for the settlement of any claim, dispute or matter arising out of or concerning this Agreement and/or its enforceability and you waive any objection to proceedings in such courts on the grounds of venue or on the grounds that proceedings have been brought in an inconvenient forum.</p>
                    <p>              Whenever possible, each provision of this Agreement will be interpreted in such a manner as to be effective and valid under applicable law but, if any provision of this Agreement is held to be invalid, illegal or unenforceable in any respect, such provision will be ineffective only to the extent of such invalidity, or unenforceability, without invalidating the remainder of this Agreement or any other provision hereof.</p>
                    <p>              This Agreement embodies the complete agreement and understanding of the parties hereto with respect to the subject matter hereof and supersedes any prior agreement or understanding between the parties in relation to such subject matter. Each of the parties acknowledges and agrees that in entering into this Agreement, it has not relied on any statement, representation, guarantee warranty, understanding, undertaking, promise or assurance (whether negligently or innocently made) of any person (whether party to this Agreement or not) other than as expressly set out in the Agreement. Each party irrevocably and unconditionally waives all claims, rights and remedies which but for this clause it might otherwise have had in relation to any of the foregoing.</p>
                    <p>              Except as explicitly provided to the contrary in this Agreement, a person who is not a party to this Agreement has no right to rely upon or enforce any term of this Agreement.</p>
                    <p>              The Company may amend any of the terms of this Agreement at any time, at its sole discretion, by posting the new version of the Agreement on its website or by sending it to you by email (without being required to notify you in any other form and/or ensuring that you have reviewed and/or received the new version). Any such amendment will enter into force on the date in which the Company posts the revised version of this Agreement on its website or sends it to you via email, unless explicitly stated otherwise. Should you wish not to be bound by the new version, you may terminate this Agreement in accordance with the provisions of Section ‎6; failure to do so will be considered as your consent to be bound by the new version.</p>
                    <p> </p>
                </div>
            </Box>
            <Box mt={2} width="100%" display="flex" justifyContent="flex-end">
                <Button variant="outlined" disabled={shouldDisableAcceptBtn} onClick={() => onConsentAccept()}>Accept</Button>
            </Box>
        </Box>
    );
};
